version: '3.8'

services:
  fastapi_app:
    image: jyothiswaroopreddy07/trade-api:latest
    container_name: trade-api-app
    restart: always
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=orders
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: trade-api-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=orders
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
